# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age_level', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=2)),
                ('occupation', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attitude', models.IntegerField()),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.Citizen')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('type', models.IntegerField()),
                ('who', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sc.Tweet'),
        ),
    ]
