# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-29 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='who',
            field=models.BooleanField(),
        ),
    ]
