# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-30 18:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0002_auto_20161029_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 30, 18, 56, 22, 155530, tzinfo=utc), verbose_name='Create Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result',
            name='create_time',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 30, 18, 57, 14, 423606, tzinfo=utc), verbose_name='Create Time'),
            preserve_default=False,
        ),
    ]
