# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0004_auto_20161031_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='gender',
            field=models.IntegerField(),
        ),
    ]
