# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-31 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sc', '0005_auto_20161031_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='who',
            field=models.IntegerField(),
        ),
    ]
